ifeq ($(CONFIG_PLATFORM_ARM_NUC980), y)
EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
EXTRA_CFLAGS += -DCONFIG_RADIO_WORK
EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE

ARCH ?= arm

CROSS_COMPILE := $(CROSS)
KSRC := $(LINUX_KERNEL_PATH)

endif
